"""
Example client that sends a rerank request to the Celery worker.

Prerequisites:
  1. Redis (or your configured broker) is running
  2. The worker is running:
     celery -A oscar.best_rerank.reranker_server worker --pool=solo --loglevel=info
  3. Run this script:
     python -m oscar.best_rerank.reranker_example_client
"""

from oscar.best_rerank.reranker_server import rerank

goal = (
    "To improve the generalization of hand gesture recognition from wearable"
    " electromyography signals by aligning their representations with"
    " high-quality, semantically rich data from other structural modalities."
)

insights = [
    "Wearable EMG signals often lack the semantic richness and signal-to-noise ratio found in other structural modalities, such as vision or high-fidelity IMU data, limiting their standalone generalization.",
    "Simple late-stage fusion is insufficient; a progressive, hierarchical fusion strategy is needed to capture complex, multi-scale interactions between modalities throughout the feature extraction process.",
    "While sEMG captures muscle activation, it lacks the explicit spatial and structural information present in vision-based modalities like hand pose or video.",
    "Supervising sEMG feature extraction with high-quality data from other modalities through cross-modal knowledge distillation can bridge the semantic gap and enrich the sEMG representations.",
    "A multi-stage training approach is necessary to first stabilize the internal sEMG feature space before attempting to align it with complex external modal data.",
    "Standard neural network architectures are not optimized for the specific sparse and multichannel structure of wearable sEMG, necessitating a custom spatial-temporal encoder like sEMGXCM.",
    "Directly classifying a large set of hand gestures from sEMG signals is computationally intensive and prone to poor generalization due to high signal variability.",
    "Machine vision can act as a high-fidelity reference modality to provide structural and semantic context that sEMG signals lack in isolation.",
    "A hierarchical classification approach, where gestures are first grouped into coarse categories before fine-grained identification, can simplify the learning objective for the sEMG model.",
    "Utilizing a specialized colored glove allows for a reliable vision-based pre-classification step, partitioning ten gestures into five manageable categories.",
    "To achieve high accuracy within these categories, basic time-domain features of sEMG signals may be insufficient to capture the subtle nuances of muscle activation.",
    "Integrating frequency-domain features with time-domain features provides a more robust and comprehensive representation of the electromyography signal, enhancing the discriminatory power of the K-Nearest Neighbor classifier.",
    "A cascaded transformer-based fusion branch can adaptively model the similarities and dependencies between different modality features more effectively than static aggregation methods.",
    "Conducting a comparative analysis between feature sets is essential to validate that multi-domain feature fusion actually improves the alignment and recognition performance over standard methods.",
    "To improve the performance of the unimodal EMG branch, the 'interactive knowledge' generated by the multimodal fusion must be explicitly mapped back to the unimodal representations.",
    "Effective cross-modal alignment requires constraints at different levels of abstraction: the embedding space for feature-level similarity and the probability space for categorical consistency.",
    "Supervised contrastive learning can be adapted to cross-modal contexts to ensure that different representations of the same gesture are clustered together while distinct gestures are separated.",
    "Online distillation allows the model to treat the multimodal fusion branch as a dynamic teacher, supervising the unimodal branches in real-time to internalize multimodal insights.",
    "Practical wearable applications require a flexible architecture where the system remains operational even when certain sensor modalities are unavailable or signals are lost.",
    "Raw sEMG signals are highly susceptible to noise and inter-trial variability, which prevents simple classifiers from generalizing across different users and sessions.",
    "Contrastive learning, specifically through mutual information maximization, can be leveraged to filter out trial-specific noise and extract features that are consistent across different sessions of the same gesture.",
]

if __name__ == "__main__":
    print("Sending rerank task to Celery worker...")
    result = rerank.delay(goal=goal, insights=insights)
    print("Task ID: {}".format(result.id))

    print("Waiting for result...")
    ranked = result.get(timeout=120)

    print("\n" + "=" * 80)
    for row in ranked:
        print("#{rank} | score={predicted_score:.4f} | {insight}".format(**row))
        print("-" * 80)
