"""
Output formatting for ResearchAgent.

Converts structured JSON outputs from ResearchAgent's three-phase pipeline
into markdown format compatible with Horizon Bench's evaluation framework.
"""

from research_agent.models.schemas import (
    ProblemIdentification,
    MethodDevelopment,
    ExperimentDesign,
    ValidationScores,
)


def format_validation_scores(scores: ValidationScores, phase_name: str) -> str:
    """
    Format validation scores as markdown.

    Args:
        scores: ValidationScores object
        phase_name: Name of the phase (for header)

    Returns:
        Formatted markdown string
    """
    lines = [f"#### {phase_name} Validation Scores"]
    lines.append(f"**Average Score**: {scores.average_score:.1f}/10.0")
    lines.append("")

    for metric_score in scores.scores:
        lines.append(f"- **{metric_score.metric_name}**: {metric_score.score:.1f}/10.0")
        if metric_score.feedback:
            # Indent feedback
            feedback_lines = metric_score.feedback.split("\n")
            for line in feedback_lines:
                lines.append(f"  {line}")

    lines.append("")
    lines.append(f"**Overall Feedback**: {scores.overall_feedback}")
    lines.append("")

    return "\n".join(lines)


def format_research_agent_output(
    problem: ProblemIdentification,
    method: MethodDevelopment,
    experiment: ExperimentDesign,
    problem_validation: ValidationScores,
    method_validation: ValidationScores,
    experiment_validation: ValidationScores,
) -> str:
    """
    Convert ResearchAgent structured output to Horizon Bench markdown format.

    This format is compatible with the evaluation pipeline's target extraction.

    Args:
        problem: Problem identification output
        method: Method development output
        experiment: Experiment design output
        problem_validation: Validation scores for problem
        method_validation: Validation scores for method
        experiment_validation: Validation scores for experiment

    Returns:
        Markdown-formatted string suitable for Horizon Bench evaluation
    """
    lines = []

    # ===== Header =====
    lines.append("# Research Idea Generated by ResearchAgent")
    lines.append("")

    # ===== Phase 1: Problem Statement =====
    lines.append("## Problem Statement")
    lines.append("")
    lines.append(problem.statement)
    lines.append("")

    if problem.background:
        lines.append("### Background")
        lines.append(problem.background)
        lines.append("")

    lines.append("### Rationale")
    lines.append(problem.rationale)
    lines.append("")

    lines.append("### Novelty")
    lines.append(problem.novelty)
    lines.append("")

    # ===== Phase 2: Proposed Method =====
    lines.append("## Proposed Method")
    lines.append("")

    lines.append("### Technical Approach")
    lines.append(method.technical_approach)
    lines.append("")

    lines.append("### Key Innovations")
    lines.append(method.key_innovations)
    lines.append("")

    lines.append("### Assumptions")
    lines.append(method.assumptions)
    lines.append("")

    if method.expected_advantages:
        lines.append("### Expected Advantages")
        lines.append(method.expected_advantages)
        lines.append("")

    # ===== Phase 3: Experiment Design =====
    lines.append("## Experiment Design")
    lines.append("")

    lines.append("### Experimental Setup")
    lines.append(experiment.setup)
    lines.append("")

    lines.append("### Evaluation Metrics")
    lines.append(experiment.metrics)
    lines.append("")

    lines.append("### Expected Results")
    lines.append(experiment.expected_results)
    lines.append("")

    if experiment.baselines:
        lines.append("### Baselines")
        lines.append(experiment.baselines)
        lines.append("")

    # ===== Validation Scores Section =====
    lines.append("---")
    lines.append("")
    lines.append("## Validation Scores")
    lines.append("")
    lines.append("The following scores were generated during ResearchAgent's iterative refinement process.")
    lines.append("")

    # Problem validation
    lines.append(format_validation_scores(problem_validation, "Problem Identification"))

    # Method validation
    lines.append(format_validation_scores(method_validation, "Method Development"))

    # Experiment validation
    lines.append(format_validation_scores(experiment_validation, "Experiment Design"))

    return "\n".join(lines)


def format_research_output_compact(
    problem: ProblemIdentification,
    method: MethodDevelopment,
    experiment: ExperimentDesign,
) -> str:
    """
    Compact formatting without validation scores (for debugging or quick view).

    Args:
        problem: Problem identification output
        method: Method development output
        experiment: Experiment design output

    Returns:
        Compact markdown string
    """
    lines = []

    lines.append("**Problem**: " + problem.statement)
    lines.append("")
    lines.append("**Method**: " + method.technical_approach)
    lines.append("")
    lines.append("**Experiment**: " + experiment.setup)
    lines.append("")

    return "\n".join(lines)
